[package]
name = "solana-config-interface"
description = "Solana config program interface."
documentation = "https://docs.rs/solana-config-interface"
version = "2.0.0"
authors = { workspace = true }
repository = { workspace = true }
license-file = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-instruction = { version = "3.5.0", optional = true }
solana-pubkey = { version = "4.3.0" }
solana-sdk-ids = { version = "3.1.0" }
solana-short-vec = { version = "3.3.0", optional = true }
solana-system-interface = { version = "3.3.0", optional = true }
wincode = { version = "0.6.1", optional = true, default-features = false, features = [
    "alloc",
    "derive",
] }

[dev-dependencies]
bincode = { workspace = true }

[features]
bincode = [
    "dep:bincode",
    "dep:solana-instruction",
    "dep:solana-system-interface",
    "serde",
    "solana-instruction/bincode",
    "solana-system-interface/bincode",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:solana-short-vec",
    "solana-pubkey/serde",
]
wincode = [
    "dep:solana-instruction",
    "dep:solana-short-vec",
    "dep:solana-system-interface",
    "dep:wincode",
    "solana-instruction/wincode",
    "solana-pubkey/wincode",
    "solana-short-vec/wincode",
    "solana-system-interface/wincode",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
